package tr.gov.nvi.kps._2021._04._01;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-08-17T12:43:51.691+03:00
 * Generated source version: 3.4.4
 *
 */
@WebServiceClient(name = "BilesikKutukSorgulaKimlikNoServis",
                  wsdlLocation = "classpath:wsdl/BilesikKutukSorgulaKimlikNoServis.wsdl",
                  targetNamespace = "http://kps.nvi.gov.tr/2021/04/01")
public class BilesikKutukSorgulaKimlikNoServis_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://kps.nvi.gov.tr/2021/04/01", "BilesikKutukSorgulaKimlikNoServis");
    public final static QName CustomBindingBilesikKutukSorgulaKimlikNoServis = new QName("http://kps.nvi.gov.tr/2021/04/01", "CustomBinding_BilesikKutukSorgulaKimlikNoServis");
    static {
        URL url = BilesikKutukSorgulaKimlikNoServis_Service.class.getClassLoader().getResource("wsdl/BilesikKutukSorgulaKimlikNoServis.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(BilesikKutukSorgulaKimlikNoServis_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/BilesikKutukSorgulaKimlikNoServis.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BilesikKutukSorgulaKimlikNoServis_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BilesikKutukSorgulaKimlikNoServis_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BilesikKutukSorgulaKimlikNoServis_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public BilesikKutukSorgulaKimlikNoServis_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BilesikKutukSorgulaKimlikNoServis_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BilesikKutukSorgulaKimlikNoServis_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns BilesikKutukSorgulaKimlikNoServis
     */
    @WebEndpoint(name = "CustomBinding_BilesikKutukSorgulaKimlikNoServis")
    public BilesikKutukSorgulaKimlikNoServis getCustomBindingBilesikKutukSorgulaKimlikNoServis() {
        return super.getPort(CustomBindingBilesikKutukSorgulaKimlikNoServis, BilesikKutukSorgulaKimlikNoServis.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BilesikKutukSorgulaKimlikNoServis
     */
    @WebEndpoint(name = "CustomBinding_BilesikKutukSorgulaKimlikNoServis")
    public BilesikKutukSorgulaKimlikNoServis getCustomBindingBilesikKutukSorgulaKimlikNoServis(WebServiceFeature... features) {
        return super.getPort(CustomBindingBilesikKutukSorgulaKimlikNoServis, BilesikKutukSorgulaKimlikNoServis.class, features);
    }

}
